// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWsNvqUENtuNMqIoo38pAYIOvkPBLZlqY',
    appId: '1:519233427923:web:bcaddbade1c2000a1c7726',
    messagingSenderId: '519233427923',
    projectId: 'take-order-app',
    authDomain: 'take-order-app.firebaseapp.com',
    storageBucket: 'take-order-app.appspot.com',
    measurementId: 'G-MG6L0JP370',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCY_9mlFqy7xPQDMUlCq4Md4r1_n-OKHa4',
    appId: '1:519233427923:android:8a57c62fd583bc801c7726',
    messagingSenderId: '519233427923',
    projectId: 'take-order-app',
    storageBucket: 'take-order-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDg6QvytJ1hiWTbos2MpnexRClw4TvWvPQ',
    appId: '1:519233427923:ios:90bbde7a570c9d471c7726',
    messagingSenderId: '519233427923',
    projectId: 'take-order-app',
    storageBucket: 'take-order-app.appspot.com',
    iosBundleId: 'com.example.adminDashboard',
  );
}
